# -*- coding: utf-8 -*-
"""20230913_A888168.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XoQc-EVLfMOIzEl5tR4VQFj0TXhXCpN-
"""

3**211